
import styles from '../styles/Home.module.css'
import useProducts from '../hooks/use-product'

const Home = () => {
  const {data: products, error, create, remove } = useProducts();
  if(!products) return <div>Loading...</div>
  if(error) return <div>error</div>
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Website bán sách</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main className={styles.main}> Main</main>
     <Footer/>
     {data.map} */}
     {products.map((product: any, index :any) => {
      <div key={index} >
        {product.name } <button onClick={() => remove(product.id)}>Delete</button>
        </div>

     })}
     <button onClick={() => create({id:10, name: "Product 1000"})}>Create</button>
     </div>
  )
}

export default Home
